### ISSUE TITLE
ANIs over 100

### ISSUE THREAD

**Issue by alexlinz** [dshrade1/Average-Nucleotide-Identity#1]
I found the problem - R is reading the ANI values in as factors, so that when I want to export the matrix as a .csv, I get the factor levels instead of the numeric values.

I fixed this by adding the following to line 17 of ANI_table_to_matrix.R:
ani1[,3] <- as.numeric(levels(ani[,3]))[ani[,3]]

**Comment by graceshrader** [comment]
Thanks, Alex! I updated the code to include the conversion to numeric.
